# Generated by Django 6.0.5 on 2026-06-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_tools', '0005_fix_execution_rule_evaluation_fk'),
        ('agent_tools', '0005_mcpserverconfig'),
    ]

    operations = [
    ]
