# Generated by Django 6.0.5 on 2026-06-24 15:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_tools", "0005_mcpserverconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="SopFieldMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sop_field",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("systems", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "sop_field_mapping",
                "ordering": ["sop_field"],
            },
        ),
    ]
