# Generated by Django 6.0.5 on 2026-06-24 15:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_tools", "0006_sopfieldmapping_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimOntologyField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("namespace", models.CharField(db_index=True, max_length=128)),
                ("canonical_field", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("aliases", models.JSONField(default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "claim_ontology_field",
                "ordering": ["namespace", "canonical_field"],
            },
        ),
        migrations.AlterModelOptions(
            name="sopfieldmapping",
            options={"ordering": ["category", "sop_field"]},
        ),
        migrations.AddField(
            model_name="sopfieldmapping",
            name="category",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="sopfieldmapping",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="claimontologyfield",
            constraint=models.UniqueConstraint(
                fields=("namespace", "canonical_field"),
                name="uniq_ontology_namespace_field",
            ),
        ),
    ]
