# Generated by Django 6.0.5 on 2026-06-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "agent_tools",
            "0007_claimontologyfield_alter_sopfieldmapping_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="noderulebinding",
            new_name="node_rule_b_shape_i_2fc2b1_idx",
            old_name="agent_tools_nrb_shape_ord_idx",
        ),
        migrations.RenameIndex(
            model_name="noderulebinding",
            new_name="node_rule_b_sop_id_4de4c4_idx",
            old_name="agent_tools_nrb_sop_key_idx",
        ),
        migrations.RenameIndex(
            model_name="nodetoolbinding",
            new_name="node_tool_b_shape_i_19fb1a_idx",
            old_name="agent_tools_ntb_shape_ord_idx",
        ),
        migrations.RenameIndex(
            model_name="nodetoolbinding",
            new_name="node_tool_b_tool_id_005551_idx",
            old_name="agent_tools_ntb_tool_idx",
        ),
        migrations.RenameIndex(
            model_name="nodetoolbinding",
            new_name="node_tool_b_rule_bi_e8e9ca_idx",
            old_name="agent_tools_ntb_rb_idx",
        ),
        migrations.RenameIndex(
            model_name="tool",
            new_name="tool_kind_307860_idx",
            old_name="agent_tools_tool_kind_act_idx",
        ),
    ]
