# Generated by Django 6.0.5 on 2026-06-28 15:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_tools", "0010_mcp_tool_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="CbdToolConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(default="cbd-medicare-config", max_length=128),
                ),
                ("medicare_group_names", models.JSONField(blank=True, default=list)),
                ("medicare_plan_names", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "cbd_tool_config",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
    ]
