# Generated by Django 6.0.5 on 2026-05-27 04:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_tools', '0004_move_to_agent_tools_schema'),
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchExecutionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_filename', models.CharField(blank=True, default='', max_length=512)),
                ('claim_id_column', models.CharField(default='claim_id', max_length=128)),
                ('total_claims', models.PositiveIntegerField(default=0)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='RUNNING', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_batches', to='builder.workflow')),
            ],
            options={
                'db_table': 'execution_batch_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleExecutionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('claim_payload', models.JSONField(blank=True, default=dict)),
                ('raw_fetch', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TERMINATED_EARLY', 'Terminated early (DENY/STOP rule on a shape)'), ('FETCH_FAILED', 'Claim fetch failed')], default='RUNNING', max_length=32)),
                ('final_decision_type', models.CharField(blank=True, default='', max_length=32)),
                ('applied_codes', models.JSONField(blank=True, default=list)),
                ('narrative', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='execution_app.batchexecutionrun')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_runs', to='builder.workflow')),
            ],
            options={
                'db_table': 'execution_rule_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('rule_key', models.CharField(db_index=True, max_length=255)),
                ('rule_source', models.CharField(choices=[('PRECONDITION', 'Precondition'), ('DECISION', 'Decision')], default='DECISION', max_length=16)),
                ('condition', models.TextField(blank=True, default='')),
                ('action', models.TextField(blank=True, default='')),
                ('matched', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('decision_type', models.CharField(blank=True, default='', max_length=32)),
                ('codes', models.JSONField(blank=True, default=list)),
                ('tool_results_used', models.JSONField(blank=True, default=list)),
                ('llm_provider', models.CharField(blank=True, default='', max_length=32)),
                ('llm_ms', models.PositiveIntegerField(default=0)),
                ('rule_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agent_tools.noderulebinding')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='execution_app.ruleexecutionrun')),
            ],
            options={
                'db_table': 'execution_rule_evaluation',
                'ordering': ['run', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='ToolInvocationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, max_length=255)),
                ('phase', models.CharField(choices=[('FETCH', 'Fetch'), ('PARSE', 'Parse'), ('EVALUATE', 'Evaluate')], default='EVALUATE', max_length=16)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('ok', models.BooleanField(default=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_invocations', to='execution_app.ruleexecutionrun')),
                ('tool_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agent_tools.nodetoolbinding')),
            ],
            options={
                'db_table': 'execution_tool_invocation',
                'ordering': ['run', 'called_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ruleexecutionrun',
            index=models.Index(fields=['batch', 'claim_id'], name='execution_r_batch_i_40c0dd_idx'),
        ),
    ]
