# Generated by Django 6.0.5 on 2026-06-10 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0002_alter_shape_label"),
        ("execution_app", "0004_ruleevaluation_skipped"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("claim_id", models.CharField(db_index=True, max_length=128)),
                ("runs_count", models.PositiveIntegerField(default=0)),
                (
                    "last_decision_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("last_narrative", models.TextField(blank=True, default="")),
                (
                    "claim_payload_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("rule_memory", models.JSONField(blank=True, default=dict)),
                ("tool_memory", models.JSONField(blank=True, default=dict)),
                ("run_history", models.JSONField(blank=True, default=list)),
                ("drift", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "execution_claim_memory",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="claimtrace",
            new_name="execution_c_claim_i_4d09eb_idx",
            old_name="execution_c_claim_i_idx",
        ),
        migrations.AddField(
            model_name="ruleevaluation",
            name="live_result",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ruleevaluation",
            name="overridden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="toolinvocationrecord",
            name="reused_from_run",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claimmemory",
            name="last_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="execution_app.ruleexecutionrun",
            ),
        ),
        migrations.AddField(
            model_name="claimmemory",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claim_memories",
                to="builder.workflow",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="claimmemory",
            unique_together={("claim_id", "workflow")},
        ),
    ]
