# Generated by Django 6.0.5 on 2026-06-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("execution_app", "0005_ruleeval_override_state"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="claimtrace",
            new_name="execution_c_claim_i_4d09eb_idx",
            old_name="execution_c_claim_i_idx",
        ),
    ]
