# Generated by Django 6.0.5 on 2026-06-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution_app", "0007_reconcile_ruleeval_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleexecutionrun",
            name="claim_lob",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
