# Generated by Django 6.0.5 on 2026-06-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution_app", "0007_claimmemory_sop_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleevaluation",
            name="injected_context",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
