# Generated by Django 6.0.5 on 2026-06-24 08:08
#
# The claim_id index was already created under the auto-generated name
# (execution_c_claim_i_4d09eb_idx) on databases that never had the explicit
# name from 0003_claimtrace. Sync Django state only.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution_app', '0009_ruleexecutionrun_review_dates'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='claimtrace',
                    new_name='execution_c_claim_i_4d09eb_idx',
                    old_name='execution_c_claim_i_idx',
                ),
            ],
        ),
    ]
