# Generated by Django 6.0.5 on 2026-07-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution_app', '0008_ruleevaluation_injected_context'),
        ('execution_app', '0013_toolinvocation_reused_from_run'),
    ]

    operations = [
    ]
