# Generated by Django 6.0.5 on 2026-07-03 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_app', '0013_toolinvocation_reused_from_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_id', models.CharField(db_index=True, max_length=128)),
                ('sop_id', models.CharField(blank=True, default='', max_length=64)),
                ('sop_title', models.CharField(blank=True, default='', max_length=512)),
                ('runs_count', models.PositiveIntegerField(default=0)),
                ('last_decision_type', models.CharField(blank=True, default='', max_length=32)),
                ('last_narrative', models.TextField(blank=True, default='')),
                ('claim_payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('rule_memory', models.JSONField(blank=True, default=dict)),
                ('tool_memory', models.JSONField(blank=True, default=dict)),
                ('run_history', models.JSONField(blank=True, default=list)),
                ('drift', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='execution_app.ruleexecutionrun')),
            ],
            options={
                'db_table': 'execution_claim_memory',
                'ordering': ['-updated_at'],
                'unique_together': {('claim_id', 'sop_id')},
            },
        ),
    ]
