# Generated by Django 6.0.5 on 2026-07-01 12:06
 
from django.db import migrations, models
 
 
class Migration(migrations.Migration):
 
    dependencies = [
        ('execution_app', '0014_merge_20260703_0826'),
    ]
 
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE execution_rule_run
                    ADD COLUMN IF NOT EXISTS cost_breakdown jsonb NOT NULL DEFAULT '{}'::jsonb;
                    """,
                    reverse_sql="""
                    ALTER TABLE execution_rule_run
                    DROP COLUMN IF EXISTS cost_breakdown;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE execution_rule_run
                    ADD COLUMN IF NOT EXISTS total_completion_tokens bigint NOT NULL DEFAULT 0;
                    """,
                    reverse_sql="""
                    ALTER TABLE execution_rule_run
                    DROP COLUMN IF EXISTS total_completion_tokens;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE execution_rule_run
                    ADD COLUMN IF NOT EXISTS total_cost_usd numeric(10,4) NOT NULL DEFAULT 0;
                    """,
                    reverse_sql="""
                    ALTER TABLE execution_rule_run
                    DROP COLUMN IF EXISTS total_cost_usd;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE execution_rule_run
                    ADD COLUMN IF NOT EXISTS total_prompt_tokens bigint NOT NULL DEFAULT 0;
                    """,
                    reverse_sql="""
                    ALTER TABLE execution_rule_run
                    DROP COLUMN IF EXISTS total_prompt_tokens;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='ruleexecutionrun',
                    name='cost_breakdown',
                    field=models.JSONField(blank=True, default=dict),
                ),
                migrations.AddField(
                    model_name='ruleexecutionrun',
                    name='total_completion_tokens',
                    field=models.BigIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='ruleexecutionrun',
                    name='total_cost_usd',
                    field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name='ruleexecutionrun',
                    name='total_prompt_tokens',
                    field=models.BigIntegerField(default=0),
                ),
            ],
        ),
    ]