# Generated by Django 6.0.5 on 2026-07-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution_app', '0014_claimmemory'),
        ('execution_app', '0015_ruleexecutionrun_cost_breakdown_and_more'),
    ]

    operations = [
    ]
