# Generated by Django 6.0.6 on 2026-07-11 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution_app", "0016_merge_20260707_1723"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleexecutionrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    (
                        "TERMINATED_EARLY",
                        "Terminated early (DENY/STOP rule on a shape)",
                    ),
                    ("FETCH_FAILED", "Claim fetch failed"),
                    ("SKIPPED", "Skipped (duplicate or prior clean run)"),
                ],
                default="RUNNING",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ClaimExecutiveSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "claim_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("verdict", models.CharField(blank=True, default="", max_length=32)),
                (
                    "audit_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("headline", models.CharField(blank=True, default="", max_length=512)),
                ("overall_summary", models.TextField(blank=True, default="")),
                ("key_findings", models.JSONField(blank=True, default=list)),
                ("step_summaries", models.JSONField(blank=True, default=list)),
                (
                    "llm_provider",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("llm_model", models.CharField(blank=True, default="", max_length=64)),
                (
                    "generated_by",
                    models.CharField(blank=True, default="agent", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_summary",
                        to="execution_app.ruleexecutionrun",
                    ),
                ),
            ],
            options={
                "db_table": "execution_claim_executive_summary",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["claim_id"], name="execution_c_claim_i_595478_idx"
                    )
                ],
            },
        ),
    ]
