# Generated by Django 6.0.6 on 2026-07-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_app', '0018_ruleexecutionrun_htl_reviewer_original_auditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorebackendUser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'claims_corebackend"."app_user',
                'managed': False,
            },
        ),
    ]
