# Generated by Django 6.0.5 on 2026-05-18 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
                ("icon", models.CharField(blank=True, default="", max_length=64)),
                ("kind", models.CharField(max_length=24)),
                ("value", models.CharField(blank=True, default="—", max_length=64)),
                ("query", models.CharField(blank=True, default="", max_length=255)),
                (
                    "color_class",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "builder_dashboard_widget",
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="NavItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="lucide-react icon name, e.g. 'GitBranch'",
                        max_length=64,
                    ),
                ),
                ("href", models.CharField(max_length=255)),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sidebar group header, e.g. 'Automation'",
                        max_length=64,
                    ),
                ),
                (
                    "min_role",
                    models.CharField(
                        choices=[("MEMBER", "Member"), ("ADMIN", "Admin")],
                        default="MEMBER",
                        max_length=16,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "builder_nav_item",
                "ordering": ["section", "order", "label"],
            },
        ),
        migrations.CreateModel(
            name="ShapeCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "builder_shape_category",
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="WorkArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                ("color", models.CharField(blank=True, default="", max_length=24)),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("width", models.FloatField(default=1200)),
                ("height", models.FloatField(default=800)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "builder_work_area",
                "ordering": ["workflow", "order"],
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("owner_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "owner_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
            ],
            options={
                "db_table": "builder_workflow",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ShapeDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                ("kind", models.CharField(max_length=64)),
                ("svg_path", models.TextField(blank=True, default="")),
                ("viewbox", models.CharField(default="0 0 100 100", max_length=64)),
                (
                    "default_label",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("default_width", models.FloatField(default=120)),
                ("default_height", models.FloatField(default=80)),
                ("default_style", models.JSONField(blank=True, default=dict)),
                ("ports", models.JSONField(blank=True, default=list)),
                ("property_schema", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shapes",
                        to="builder.shapecategory",
                    ),
                ),
            ],
            options={
                "db_table": "builder_shape_definition",
                "ordering": ["category", "order", "label"],
            },
        ),
        migrations.CreateModel(
            name="Workbench",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "node_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("kind", models.CharField(blank=True, default="", max_length=64)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("order", models.PositiveIntegerField(default=0)),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("width", models.FloatField(default=160)),
                ("height", models.FloatField(default=80)),
                ("style", models.JSONField(blank=True, default=dict)),
                (
                    "work_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workbenches",
                        to="builder.workarea",
                    ),
                ),
            ],
            options={
                "db_table": "builder_workbench",
                "ordering": ["work_area", "order"],
            },
        ),
        migrations.CreateModel(
            name="Shape",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("width", models.FloatField(default=120)),
                ("height", models.FloatField(default=80)),
                ("style", models.JSONField(blank=True, default=dict)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="builder.shapedefinition",
                    ),
                ),
                (
                    "workbench",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shapes",
                        to="builder.workbench",
                    ),
                ),
            ],
            options={
                "db_table": "builder_shape",
                "ordering": ["workbench", "order"],
            },
        ),
        migrations.AddField(
            model_name="workarea",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_areas",
                to="builder.workflow",
            ),
        ),
        migrations.CreateModel(
            name="ShapeConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_port",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "target_port",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "condition_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("waypoints", models.JSONField(blank=True, default=list)),
                ("style", models.JSONField(blank=True, default=dict)),
                (
                    "source_shape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing",
                        to="builder.shape",
                    ),
                ),
                (
                    "target_shape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming",
                        to="builder.shape",
                    ),
                ),
            ],
            options={
                "db_table": "builder_shape_connection",
                "indexes": [
                    models.Index(
                        fields=["source_shape"], name="builder_sha_source__e7e2e2_idx"
                    ),
                    models.Index(
                        fields=["target_shape"], name="builder_sha_target__72e85c_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="workbench",
            index=models.Index(
                fields=["work_area", "order"], name="builder_wor_work_ar_73e8db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workbench",
            index=models.Index(fields=["kind"], name="builder_wor_kind_d46792_idx"),
        ),
        migrations.AddIndex(
            model_name="shape",
            index=models.Index(
                fields=["workbench", "order"], name="builder_sha_workben_c8fa37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workarea",
            index=models.Index(
                fields=["workflow", "order"], name="builder_wor_workflo_7fe895_idx"
            ),
        ),
    ]
