# Generated by Django 6.0.5 on 2026-06-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shape",
            name="label",
            field=models.TextField(blank=True, default=""),
        ),
    ]
