# Generated by Django 6.0.6 on 2026-08-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_seed_parallel_shapes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbench',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='workbench',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workflow',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='workbench',
            index=models.Index(fields=['node_key', 'is_current'], name='builder_wor_node_ke_111b7e_idx'),
        ),
    ]
