# Generated by Django 6.0.5 on 2026-08-20 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_backfill_workflow_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowVersionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shape_id', models.UUIDField()),
                ('shape_label', models.CharField(blank=True, default='', max_length=255)),
                ('workbench_id', models.UUIDField()),
                ('node_key', models.CharField(blank=True, default='', max_length=128)),
                ('rule_key', models.CharField(db_index=True, max_length=255)),
                ('is_custom', models.BooleanField(default=False)),
                ('condition', models.TextField(blank=True, default='')),
                ('action', models.TextField(blank=True, default='')),
                ('decision_type', models.CharField(blank=True, default='', max_length=64)),
                ('codes', models.JSONField(blank=True, default=list)),
                ('subrule_id', models.CharField(blank=True, default='', max_length=64)),
                ('sop_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sop_title', models.CharField(blank=True, default='', max_length=255)),
                ('sop_version_number', models.PositiveIntegerField(blank=True, null=True)),
                ('references_json', models.JSONField(blank=True, default=list)),
                ('excluded_by_json', models.JSONField(blank=True, default=list)),
                ('html_reference_json', models.JSONField(blank=True, default=dict)),
                ('orphaned_from_rule_key', models.CharField(blank=True, default='', max_length=255)),
                ('orphaned_from_sop_id', models.PositiveIntegerField(blank=True, null=True)),
                ('orphaned_reason', models.CharField(blank=True, default='', max_length=64)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='builder.workflowversion')),
            ],
            options={
                'db_table': 'builder_workflow_version_rule',
                'constraints': [models.UniqueConstraint(fields=('workflow_version', 'shape_id', 'rule_key'), name='uniq_wfv_rule')],
            },
        ),
    ]
