# Generated by Django 6.0.5 on 2026-08-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_workflow_version_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowversionrule',
            name='shape_label',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workflowversionrule',
            name='sop_title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
