# Generated by Django 6.0.5 on 2026-08-20 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_workflow_version_rule_textfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowVersionTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shape_id', models.UUIDField()),
                ('workbench_id', models.UUIDField()),
                ('node_key', models.CharField(blank=True, default='', max_length=128)),
                ('tool_id', models.UUIDField(blank=True, null=True)),
                ('tool_name', models.CharField(blank=True, default='', max_length=255)),
                ('rule_key', models.CharField(blank=True, default='', max_length=255)),
                ('args_template', models.JSONField(blank=True, default=dict)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_bindings', to='builder.workflowversion')),
            ],
            options={
                'db_table': 'builder_workflow_version_tool',
            },
        ),
    ]
