# Generated by Django 6.0.5 on 2026-05-17 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sop_ingestion", "0002_pipeline_logs"),
    ]

    operations = [
        migrations.CreateModel(
            name="CtxCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_value", models.CharField(max_length=64)),
                ("code_system", models.CharField(max_length=32)),
                ("context_snippet", models.TextField(blank=True)),
                ("source_field", models.CharField(blank=True, max_length=128)),
                ("confidence", models.FloatField(default=1.0)),
                ("description", models.TextField(blank=True)),
                ("allow_code", models.CharField(blank=True, max_length=16)),
                ("deny_code", models.CharField(blank=True, max_length=16)),
            ],
            options={
                "verbose_name": "Ctx Code",
            },
        ),
        migrations.CreateModel(
            name="CtxDateCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.CharField(blank=True, max_length=32)),
                ("date_to", models.CharField(blank=True, max_length=32)),
                ("effective_date", models.CharField(blank=True, max_length=32)),
                ("context", models.TextField(blank=True)),
                ("source_field", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "verbose_name": "Ctx Date Condition",
            },
        ),
        migrations.CreateModel(
            name="CtxGroupRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=256)),
                ("network_type", models.CharField(default="BOTH", max_length=8)),
                ("limit_days", models.SmallIntegerField(blank=True, null=True)),
                ("limit_months", models.SmallIntegerField(blank=True, null=True)),
                ("limit_years", models.SmallIntegerField(blank=True, null=True)),
                ("inn_days", models.SmallIntegerField(blank=True, null=True)),
                ("oon_days", models.SmallIntegerField(blank=True, null=True)),
                ("calculation_from", models.CharField(default="DOS", max_length=32)),
                ("member_submitted_only", models.BooleanField(default=False)),
                ("special_notes", models.JSONField(default=list)),
                ("raw_text", models.TextField(blank=True)),
                ("exceptions", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Ctx Group Rule",
            },
        ),
        migrations.CreateModel(
            name="CtxUnresolved",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_url", models.TextField(blank=True)),
                ("link_text", models.TextField(blank=True)),
                ("raw_href", models.CharField(blank=True, max_length=2048)),
                ("resolution_hint", models.TextField(blank=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ctx Unresolved Link",
            },
        ),
        migrations.CreateModel(
            name="SopDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField()),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("doc_format", models.CharField(max_length=8)),
                ("title", models.TextField(blank=True)),
                ("effective_date", models.CharField(blank=True, max_length=32)),
                ("revision_date", models.CharField(blank=True, max_length=32)),
                ("platform", models.CharField(blank=True, max_length=128)),
                ("state_div", models.CharField(blank=True, max_length=128)),
                ("crawl_depth", models.PositiveSmallIntegerField(default=0)),
                ("parent_url", models.TextField(blank=True)),
                ("step_count", models.PositiveIntegerField(default=0)),
                ("rule_count", models.PositiveIntegerField(default=0)),
                ("pre_section_count", models.PositiveIntegerField(default=0)),
                ("code_count", models.PositiveIntegerField(default=0)),
                ("raw_text", models.TextField(blank=True)),
                ("parse_warnings", models.JSONField(default=list)),
                ("sop_id", models.CharField(blank=True, max_length=256)),
                ("is_current", models.BooleanField(default=True)),
                ("crawled_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SOP Document",
            },
        ),
        migrations.CreateModel(
            name="SopLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("href", models.TextField()),
                ("link_text", models.TextField(blank=True)),
                ("link_type", models.CharField(default="UNRESOLVED", max_length=32)),
                ("resolved_url", models.TextField(blank=True)),
                ("status", models.CharField(default="PENDING", max_length=16)),
            ],
            options={
                "verbose_name": "SOP Link",
            },
        ),
        migrations.CreateModel(
            name="SopPreSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("section_id", models.CharField(blank=True, max_length=128)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("items", models.JSONField(default=list)),
                ("annotations", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "SOP Pre-Section",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SopRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveSmallIntegerField()),
                ("row_index", models.PositiveSmallIntegerField(default=0)),
                ("condition_if", models.TextField(blank=True)),
                ("condition_and", models.TextField(blank=True)),
                ("action", models.TextField(blank=True)),
                ("decision", models.CharField(default="CONDITIONAL", max_length=32)),
                ("codes", models.JSONField(default=list)),
                ("skip_to_step", models.SmallIntegerField(blank=True, null=True)),
                ("routing_label", models.CharField(blank=True, max_length=128)),
                ("referenced_sops", models.JSONField(default=list)),
                ("annotations", models.JSONField(default=list)),
                ("action_line", models.TextField(blank=True)),
                ("action_claim", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "SOP Rule",
                "ordering": ["step_number", "row_index"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="ingesteddocument",
            name="unique_job_hash_v2",
        ),
        migrations.AddField(
            model_name="ingestionjob",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ingesteddocument",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ingestionjob",
            name="llm_model",
            field=models.CharField(default="claude-sonnet-4-5-20250929", max_length=64),
        ),
        migrations.AlterField(
            model_name="llmcalllog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pipelinestagelog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ingesteddocument",
            unique_together={("job", "content_hash")},
        ),
        migrations.AddField(
            model_name="ctxunresolved",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unresolved_links",
                to="sop_ingestion.ingestionjob",
            ),
        ),
        migrations.AddField(
            model_name="sopdocument",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sop_documents",
                to="sop_ingestion.ingestionjob",
            ),
        ),
        migrations.AddField(
            model_name="ctxgrouprule",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_rules",
                to="sop_ingestion.sopdocument",
            ),
        ),
        migrations.AddField(
            model_name="ctxdatecondition",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="date_conditions",
                to="sop_ingestion.sopdocument",
            ),
        ),
        migrations.AddField(
            model_name="ctxcode",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codes",
                to="sop_ingestion.sopdocument",
            ),
        ),
        migrations.AddField(
            model_name="soplink",
            name="source_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="sop_ingestion.sopdocument",
            ),
        ),
        migrations.AddField(
            model_name="soppresection",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_sections",
                to="sop_ingestion.sopdocument",
            ),
        ),
        migrations.AddField(
            model_name="soprule",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="sop_ingestion.sopdocument",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sopdocument",
            unique_together={("job", "content_hash")},
        ),
        migrations.AlterUniqueTogether(
            name="ctxcode",
            unique_together={("document", "raw_value", "code_system")},
        ),
    ]
