"""Make ``LLMCallLog.job`` nullable and add ``execution_run`` FK.

Hand-written (not generated by ``makemigrations``) so we don't pull in
unrelated drift between the ORM and the historical sop_ingestion schema
(model deletions, id-field default changes, etc.) — those are teammate
territory and will land in their own migration.

The execution engine's LLM helper writes rows here with ``job=NULL`` and
``execution_run=<RuleExecutionRun id>``; the SOP ingestion pipeline keeps
writing rows with ``job=<IngestionJob id>`` and ``execution_run=NULL``.
"""
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sop_ingestion", "0010_sop_exclusion_html_block"),
        ("execution_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmcalllog",
            name="job",
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_calls",
                to="sop_ingestion.ingestionjob",
            ),
        ),
        migrations.AddField(
            model_name="llmcalllog",
            name="execution_run",
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_calls",
                to="execution_app.ruleexecutionrun",
            ),
        ),
    ]
