"""Add rule-nesting + out-of-scope support to the audit rule tables.

Hand-written (not generated by ``makemigrations``) so we don't pull in the
unrelated historical drift between the ORM and the sop_ingestion schema
(legacy Ctx*/Sop* model deletions, id-field AutoField changes, stale
unique_together constraints) — those are teammate territory.

This migration only:
  * adds nesting fields to AuditDecision so a decision row can be a child of
    another decision row (preserves YAML subrule hierarchy, levels 0..N),
  * adds out-of-scope + provenance flags to AuditDecision and AuditStep,
  * adds the (step, parent, row_index) index used to walk the tree.

All new columns are additive and nullable/defaulted, so existing flat SOP
rows keep working (parent=NULL, depth=0, aggregation='LEAF').
"""
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sop_ingestion", "0011_llmcalllog_execution_run"),
    ]

    operations = [
        # ── AuditDecision: nesting ───────────────────────────────────────────
        migrations.AddField(
            model_name="auditdecision",
            name="parent",
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="sop_ingestion.auditdecision",
            ),
        ),
        migrations.AddField(
            model_name="auditdecision",
            name="depth",
            field=models.PositiveSmallIntegerField(default=0, db_index=True),
        ),
        migrations.AddField(
            model_name="auditdecision",
            name="subrule_id",
            field=models.CharField(max_length=64, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="auditdecision",
            name="table_name",
            field=models.CharField(max_length=256, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="auditdecision",
            name="aggregation",
            field=models.CharField(
                max_length=16, default="LEAF",
                choices=[
                    ("FIRST_MATCH", "First matching child wins"),
                    ("XOR_ONE", "Exactly one child must be Met"),
                    ("APPLICABLE_ONLY", "Only the applicable child is evaluated"),
                    ("ALWAYS_MET", "Always Met regardless of children"),
                    ("ANY", "Any matching child (lookup table)"),
                    ("LEAF", "Leaf rule — no children"),
                ],
            ),
        ),
        migrations.AddField(
            model_name="auditdecision",
            name="output_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="auditdecision",
            name="tooling_allowed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="auditdecision",
            name="is_out_of_scope",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="auditdecision",
            name="mongo_subtree_ref",
            field=models.CharField(max_length=128, blank=True, default=""),
        ),
        # ── AuditStep: out-of-scope + provenance ─────────────────────────────
        migrations.AddField(
            model_name="auditstep",
            name="is_out_of_scope",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="auditstep",
            name="yaml_rule_id",
            field=models.CharField(max_length=64, blank=True, default=""),
        ),
        # ── Meta: ordering + tree-walk index ─────────────────────────────────
        migrations.AlterModelOptions(
            name="auditdecision",
            options={"ordering": ["step__step_number", "depth", "row_index"],
                     "verbose_name": "Audit Decision"},
        ),
        migrations.AddIndex(
            model_name="auditdecision",
            index=models.Index(
                fields=["step", "parent", "row_index"],
                name="sop_ingesti_step_id_709c69_idx",
            ),
        ),
    ]
