# Generated by Django 6.0.5 on 2026-06-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_ingestion', '0013_sop_activation_review'),
        ('sop_ingestion', '0016_widen_ingesteddocument_sop_ids'),
    ]

    operations = [
    ]
