# Generated by Django 6.0.5 on 2026-06-24 08:09
#
# Hand-edited for safe apply against mixed DB history:
# - Legacy Ctx*/Sop* tables were dropped in 0004 (or never existed); state-only cleanup.
# - sop_ingestion_sopdocument may hold unrelated rows under a reused table name — do not DROP.
# - Graph indexes were created via RunSQL in 0005 under custom names; state-only index sync.
# - Named unique constraints on audit_* tables are preserved (models use UniqueConstraint).

from django.db import migrations, models


_LEGACY_STATE_OPS = [
    migrations.AlterUniqueTogether(
        name='ctxcode',
        unique_together=None,
    ),
    migrations.RemoveField(
        model_name='ctxcode',
        name='document',
    ),
    migrations.RemoveField(
        model_name='ctxdatecondition',
        name='document',
    ),
    migrations.RemoveField(
        model_name='ctxgrouprule',
        name='document',
    ),
    migrations.RemoveField(
        model_name='ctxunresolved',
        name='job',
    ),
    migrations.AlterUniqueTogether(
        name='sopdocument',
        unique_together=None,
    ),
    migrations.RemoveField(
        model_name='sopdocument',
        name='job',
    ),
    migrations.RemoveField(
        model_name='soppresection',
        name='document',
    ),
    migrations.RemoveField(
        model_name='soprule',
        name='document',
    ),
    migrations.RemoveField(
        model_name='soplink',
        name='source_document',
    ),
    migrations.DeleteModel(
        name='CtxCode',
    ),
    migrations.DeleteModel(
        name='CtxDateCondition',
    ),
    migrations.DeleteModel(
        name='CtxGroupRule',
    ),
    migrations.DeleteModel(
        name='CtxUnresolved',
    ),
    migrations.DeleteModel(
        name='SopPreSection',
    ),
    migrations.DeleteModel(
        name='SopRule',
    ),
    migrations.DeleteModel(
        name='SopDocument',
    ),
    migrations.DeleteModel(
        name='SopLink',
    ),
]

_GRAPH_INDEX_STATE_OPS = [
    migrations.AddIndex(
        model_name='auditgraphedge',
        index=models.Index(fields=['sop', 'rel_type'], name='sop_ingesti_sop_id_1ce800_idx'),
    ),
    migrations.AddIndex(
        model_name='auditgraphedge',
        index=models.Index(fields=['source', 'rel_type'], name='sop_ingesti_source__e3ebdb_idx'),
    ),
    migrations.AddIndex(
        model_name='auditgraphnode',
        index=models.Index(fields=['sop', 'node_type'], name='sop_ingesti_sop_id_515809_idx'),
    ),
]


class Migration(migrations.Migration):

    dependencies = [
        ('sop_ingestion', '0017_ingestionjob_trigger_source'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=_LEGACY_STATE_OPS,
        ),
        migrations.AlterField(
            model_name='auditannotation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditcode',
            name='code_type',
            field=models.CharField(choices=[('EOB', 'EOB Code (E/F/W)'), ('EX', 'Exception Code'), ('DENIAL', 'Denial Code'), ('SYSTEM_ACT', 'System Action (F3/F4/F5)'), ('POS', 'Place of Service'), ('REVENUE', 'Revenue Code'), ('BILL_TYPE', 'Type of Bill'), ('MODIFIER', 'Procedure Modifier'), ('FREQUENCY', 'Frequency Code'), ('CPT', 'CPT / HCPCS'), ('UNKNOWN', 'Other')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='auditcode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditdatecondition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditdecision',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditgraphedge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditgraphedge',
            name='rel_type',
            field=models.CharField(choices=[('HAS_META', 'has metadata'), ('HAS_PRE_SECTION', 'has pre-section'), ('HAS_RULE', 'has rule'), ('HAS_STEP', 'has step'), ('HAS_DECISION', 'has decision'), ('HAS_ANNOTATION', 'has annotation'), ('HAS_GROUP_LIMIT', 'has group limit'), ('HAS_CODE_REF', 'has code reference'), ('HAS_DATE_COND', 'has date condition'), ('REFERENCES', 'references other SOP'), ('GOTO', 'branches to step')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='auditgraphnode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditgraphnode',
            name='node_type',
            field=models.CharField(choices=[('DOCUMENT', 'Document'), ('META', 'Metadata'), ('PRE_SECTION', 'Pre-Section'), ('PRE_RULE', 'Pre-Section Rule'), ('STEP', 'Step'), ('DECISION', 'Decision Rule'), ('ANNOTATION', 'Annotation'), ('GROUP_LIMIT', 'Group Limit'), ('CODE', 'Claims Code'), ('DATE_COND', 'Date Condition'), ('REFERENCE', 'Cross-Reference')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='auditgrouplimit',
            name='calculation_basis',
            field=models.CharField(default='DOS', help_text='DOS, PAID_DATE, or EOB_DATE', max_length=32),
        ),
        migrations.AlterField(
            model_name='auditgrouplimit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditprecondition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditsop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditstep',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=_GRAPH_INDEX_STATE_OPS,
        ),
    ]
