# Generated by Django 6.0.5 on 2026-06-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sop_ingestion", "0020_alter_ctxcode_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="auditcode",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="auditsop",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="auditstep",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="auditcode",
            constraint=models.UniqueConstraint(
                fields=("sop", "code_value", "code_type"), name="unique_auditcode"
            ),
        ),
        migrations.AddConstraint(
            model_name="auditsop",
            constraint=models.UniqueConstraint(
                fields=("job", "content_hash"), name="unique_auditsop_job_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="auditstep",
            constraint=models.UniqueConstraint(
                fields=("sop", "step_number"), name="unique_auditstep_sop_number"
            ),
        ),
    ]
