# Generated by Django 6.0.5 on 2026-06-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sop_ingestion", "0021_alter_auditcode_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditdecision",
            name="revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="auditsop",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
