# Generated by Django 6.0.5 on 2026-07-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_ingestion', '0017_ingestionjob_trigger_source_state'),
        ('sop_ingestion', '0024_merge_sop_versioning_rebase'),
    ]

    operations = [
    ]
