# Generated by Django 6.0.5 on 2026-07-03 13:30
 
import sop_ingestion.models
from django.db import migrations, models
 
 
class Migration(migrations.Migration):
 
    dependencies = [
        ('sop_ingestion', '0024_merge_sop_versioning_rebase'),
    ]
 
    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='llm_model',
            field=models.CharField(default=sop_ingestion.models._default_job_llm_model, max_length=64),
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='llm_provider',
            field=models.CharField(default=sop_ingestion.models._default_job_llm_provider, max_length=32),
        ),
    ]
 