# Generated by Django 6.0.5 on 2026-07-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_ingestion', '0017_ingestionjob_trigger_source_state'),
        ('sop_ingestion', '0025_alter_ingestionjob_llm_model_and_more'),
    ]

    operations = [
    ]
