# Generated by Django 6.0.6 on 2026-07-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sop_ingestion", "0014_claimmemory"),
        ("sop_ingestion", "0016_merge_20260707_1723"),
        ("sop_ingestion", "0026_merge_20260707_1723"),
    ]

    operations = []
