# Generated by Django 6.0.5 on 2026-07-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_ingestion', '0027_merge_20260712_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='trigger_source',
            field=models.CharField(blank=True, default='manual', help_text='manual | workflow | revision_check', max_length=32),
        ),
        migrations.DeleteModel(
            name='ClaimMemory',
        ),
    ]
