# Generated by Django 6.0.5 on 2026-08-04 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sop_ingestion", "0028_alter_ingestionjob_trigger_source_delete_claimmemory"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleChangeSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("stale", "Stale"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True, default="")),
                (
                    "resulting_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "sop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_sets",
                        to="sop_ingestion.auditsop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule Change Set",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RuleChangeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subrule_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "display_rule_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("step_number", models.PositiveIntegerField(default=0)),
                ("row_index", models.PositiveIntegerField(default=0)),
                ("base_revision", models.PositiveIntegerField(default=1)),
                ("previous_fields", models.JSONField(blank=True, default=dict)),
                ("proposed_fields", models.JSONField(blank=True, default=dict)),
                ("dependent_steps", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_proposals",
                        to="sop_ingestion.auditdecision",
                    ),
                ),
                (
                    "changeset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="sop_ingestion.rulechangeset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule Change Proposal",
                "ordering": ["step_number", "row_index", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="rulechangeset",
            index=models.Index(
                fields=["status", "-created_at"], name="sop_ingesti_status_189dea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rulechangeset",
            index=models.Index(
                fields=["sop", "status"], name="sop_ingesti_sop_id_163a99_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rulechangeset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("sop", "created_by"),
                name="uniq_open_change_set_per_sop_author",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulechangeproposal",
            constraint=models.UniqueConstraint(
                fields=("changeset", "decision"),
                name="uniq_proposal_per_rule_per_change_set",
            ),
        ),
    ]
