# Generated by Django 6.0.5 on 2026-08-05 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0005_seed_parallel_shapes"),
        ("sop_ingestion", "0029_rulechangeset_rulechangeproposal_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rulechangeproposal",
            name="uniq_proposal_per_rule_per_change_set",
        ),
        migrations.RemoveConstraint(
            model_name="rulechangeset",
            name="uniq_open_change_set_per_sop_author",
        ),
        migrations.AddField(
            model_name="rulechangeproposal",
            name="change_kind",
            field=models.CharField(
                choices=[
                    ("modified", "Modified"),
                    ("added", "Added"),
                    ("removed", "Removed"),
                ],
                db_index=True,
                default="modified",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="rulechangeproposal",
            name="to_decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_change_proposals",
                to="sop_ingestion.auditdecision",
            ),
        ),
        migrations.AddField(
            model_name="rulechangeset",
            name="ingestion_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="change_sets",
                to="sop_ingestion.ingestionjob",
            ),
        ),
        migrations.AddField(
            model_name="rulechangeset",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual rule edit"),
                    ("ingestion", "SOP re-ingestion"),
                ],
                db_index=True,
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="rulechangeset",
            name="to_sop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_change_sets",
                to="sop_ingestion.auditsop",
            ),
        ),
        migrations.AddField(
            model_name="rulechangeset",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sop_change_sets",
                to="builder.workflow",
            ),
        ),
        migrations.AlterField(
            model_name="rulechangeproposal",
            name="decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_proposals",
                to="sop_ingestion.auditdecision",
            ),
        ),
        migrations.AddIndex(
            model_name="rulechangeset",
            index=models.Index(
                fields=["workflow", "status"], name="sop_ingesti_workflo_61210a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rulechangeproposal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("decision__isnull", False)),
                fields=("changeset", "decision"),
                name="uniq_proposal_per_from_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulechangeproposal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("to_decision__isnull", False)),
                fields=("changeset", "to_decision"),
                name="uniq_proposal_per_to_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulechangeset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open"), ("workflow__isnull", True)),
                fields=("sop", "created_by"),
                name="uniq_open_manual_change_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulechangeset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open"), ("workflow__isnull", False)),
                fields=("sop", "workflow", "created_by"),
                name="uniq_open_ingestion_change_set",
            ),
        ),
    ]
