# Generated by Django 6.0.5 on 2026-08-20 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_workflow_version_rule_textfields'),
        ('sop_ingestion', '0030_remove_rulechangeproposal_uniq_proposal_per_rule_per_change_set_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rulechangeset',
            name='uniq_open_ingestion_change_set',
        ),
        migrations.AddField(
            model_name='rulechangeproposal',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rulechangeproposal',
            name='node_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='rulechangeproposal',
            name='rule_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rulechangeproposal',
            name='shape_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rulechangeproposal',
            name='workbench_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='trigger_source',
            field=models.CharField(blank=True, default='manual', help_text='manual | workflow | revision_check', max_length=32),
        ),
        migrations.AlterField(
            model_name='rulechangeset',
            name='sop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_sets', to='sop_ingestion.auditsop'),
        ),
        migrations.AlterField(
            model_name='rulechangeset',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual rule edit'), ('ingestion', 'SOP re-ingestion'), ('canvas', 'Workflow canvas rule edit')], db_index=True, default='manual', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='rulechangeproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('shape_id__isnull', False)), fields=('changeset', 'shape_id', 'rule_key'), name='uniq_proposal_per_canvas_rule'),
        ),
        migrations.AddConstraint(
            model_name='rulechangeset',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'ingestion'), ('status', 'open'), ('workflow__isnull', False)), fields=('sop', 'workflow', 'created_by'), name='uniq_open_ingestion_change_set'),
        ),
        migrations.AddConstraint(
            model_name='rulechangeset',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'canvas'), ('status', 'open')), fields=('workflow', 'created_by'), name='uniq_open_canvas_change_set'),
        ),
    ]
